/**
 * Ronille Alcala (@nille.arts) - Artworks Catalog
 * Curated metadata for all 28 artwork assets in the images directory.
 */

const ARTWORKS = [
  {
    id: 'miles-morales',
    title: 'Across the Spider-Verse — Miles Morales',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2023',
    medium: 'Digital Illustration & Chromatic Halftone',
    primaryFile: 'HELLO! Im back with Miles! Havent watched the movie yet but Ive seen numerous artists creati.webp',
    hasProcess: false,
    featured: true,
    heroCandidate: true,
    aspectRatio: '4:5',
    caption: 'Dynamic perspective illustration capturing Miles Morales swinging through Neo-Manhattan with chromatic aberration and comic halftone styling.',
    description: 'A study in dynamic perspective, kinetic motion, and comic-book textures. Inspired by the visual language of Spider-Man: Across the Spider-Verse, balancing deep urban blues against intense magenta neon rim lights.',
    tags: ['Spider-Man', 'Marvel', 'Dynamic Motion', 'Comic Halftone']
  },
  {
    id: 'ekko-arcane',
    title: 'The Boy Who Shattered Time — Ekko',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: 'Digital Portrait & Chromatic Liquid Flow',
    primaryFile: 'The Boy who shattered TimeBest Boy of the seriesEkko fan art Style Inspired by @patrick.ganasMy.webp',
    hasProcess: false,
    featured: true,
    heroCandidate: true,
    aspectRatio: '4:5',
    caption: 'Split character portrait of Ekko from Arcane, blending stylized realism with iridescent chrome flourishes.',
    description: 'An homage to Ekko from Arcane, heavily inspired by stylized character illustrator Patrick Ganas. Exploring dual profile planes, textured dreadlock volumes, and iridescent chromatic splatter that mirrors temporal fractures.',
    tags: ['Arcane', 'League of Legends', 'Ekko', 'Stylized Realism']
  },
  {
    id: 'dabi-glow',
    title: 'Blue Flame — Toya Todoroki (Dabi)',
    category: 'Character Art',
    filterCategory: 'character-art',
    year: '2022',
    medium: 'Digital Illustration & Stylized Luminescence',
    primaryFile: 'Back to gloooww✨With new technique for semi realistic or stylized fireToya Todoroki- DabiForm M.webp',
    hasProcess: false,
    featured: true,
    aspectRatio: '4:5',
    caption: 'Moody atmospheric portrait exploring semi-realistic cobalt luminescence and glowing fire techniques.',
    description: 'A dedicated exploration of luminescent lighting on skin and folds. Using a specialized layering technique to achieve hyper-intense blue flame that casts crisp specular highlights across Dabi\'s silhouette.',
    tags: ['My Hero Academia', 'Dabi', 'Luminescence', 'Digital Painting']
  },
  {
    id: 'meltdown-surrealism',
    title: 'MELTDOWN — Severe Distress',
    category: 'Surrealism & Concept',
    filterCategory: 'surrealism',
    year: '2022',
    medium: 'Traditional Ink & Digital Color',
    primaryFile: 'MELTDOWN🕯️🫠This represents a severe, overwhelming emotional distress.Surealism ArtDrawn tradi.webp',
    processFile: 'MELTDOWN🕯️🫠This represents a severe, overwhelming emotional distress.Surealism ArtDrawn tradi (1).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Original Ink Linework',
    featured: true,
    aspectRatio: '4:5',
    caption: 'Surrealist metaphor depicting extreme emotional exhaustion and vulnerability as a melting candle portrait.',
    description: 'A deeply personal surrealist piece representing severe, overwhelming emotional distress. The piece started as an intricate traditional pen-and-ink drawing on cold-press paper with meticulous stippling, before being digitally colored with somber candlelit values.',
    tags: ['Surrealism', 'Mental Health', 'Traditional Ink', 'Process Piece']
  },
  {
    id: 'tetsuo-akira',
    title: 'Biomechanical Mutation — Tetsuo Shima (AKIRA)',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: 'Traditional Ink & Digital Screentone',
    primaryFile: 'Didnt expect to make this kind of artA fan art of Tetsuo Shima from the 1988 anime film AKIRAT.webp',
    processFile: 'Didnt expect to make this kind of artA fan art of Tetsuo Shima from the 1988 anime film AKIRAT (1).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Pure Ink Sketch',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Intricate biomechanical line art celebrating Katsuhiro Otomo\'s 1988 cyberpunk masterpiece AKIRA.',
    description: 'Tribute to Katsuhiro Otomo\'s AKIRA. The grotesque cybernetic distortion of Tetsuo\'s arm was crafted using fine-liner pens, capturing every wire, piston, and fleshy mass, accented digitally by Tetsuo\'s iconic red cape.',
    tags: ['AKIRA', 'Cyberpunk', 'Traditional Inking', 'Biomechanical']
  },
  {
    id: 'denji-bad-habit',
    title: 'Bad Habit — Denji (Chainsaw Man)',
    category: 'Character Art',
    filterCategory: 'character-art',
    year: '2022',
    medium: 'Digital Illustration & Graphic Poster Design',
    primaryFile: 'Can I bite your tongue like my bad habitDenji fan art Reference- Bad habit by Steve LacyFirst.webp',
    altFile: 'Can I bite your tongue like my bad habitDenji fan art Reference- Bad habit by Steve LacyFirst (1).webp',
    hasProcess: true,
    processType: 'full-to-crop',
    processLabel: 'Full Bleed Close-Up',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Graphic typography poster inspired by Steve Lacy\'s song Bad Habit and Chainsaw Man\'s visceral intensity.',
    description: 'A bold editorial poster layout featuring custom Japanese typography and vivid color blocking. Paired with an uncropped full-bleed portrait detailing the raw emotional delirium of Denji.',
    tags: ['Chainsaw Man', 'Denji', 'Graphic Design', 'Poster Art']
  },
  {
    id: 'cyborg-oc',
    title: 'Cybernetic Genesis — Original Cyborg OC',
    category: 'Original Concept',
    filterCategory: 'original-concept',
    year: '2022',
    medium: 'Traditional Ink & Sci-Fi Cutaway',
    primaryFile: 'New CYBORG OCConcept and style inspired by Masamune Shirows Ghost in the Shell Traditional ink.webp',
    processFile: 'New CYBORG OCConcept and style inspired by Masamune Shirows Ghost in the Shell Traditional ink (3).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Original Ink Study',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Original cyborg concept drawing inspiration from Masamune Shirow\'s Ghost in the Shell.',
    description: 'An original character concept exploring the boundary between synthetic machinery and organic life. Drawn traditionally with precision technical pens, detailing skull plates, optical mounts, and internal servomotors.',
    tags: ['Original Character', 'Ghost in the Shell', 'Sci-Fi', 'Anatomy']
  },
  {
    id: 'kaiju-no-8',
    title: 'Monstrous Rebirth — Kaiju No. 8',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: 'Traditional Drawing to Digital Grayscale',
    primaryFile: 'July Project Kaiju No. 8Traditional drawing to digital coloring using grayscale technique on Ib.webp',
    processFile: 'July Project Kaiju No. 8Traditional drawing to digital coloring using grayscale technique on Ib (1).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Grayscale Drawing',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Grayscale-to-color rendering study executed on IbisPaint, emphasizing monstrous muscular anatomy.',
    description: 'A study in the grayscale-to-color workflow on mobile digital canvas. Started with graphite line art and shaded values before overlaying luminescent cyan veins and intense textured rim lighting.',
    tags: ['Kaiju No. 8', 'Grayscale Technique', 'IbisPaint', 'Creature Art']
  },
  {
    id: 'bunz-hitman-rabbit',
    title: 'BUNZ — The Hitman Rabbit',
    category: 'Original Concept',
    filterCategory: 'original-concept',
    year: '2022',
    medium: 'Mixed Media (Traditional Ink + Digital)',
    primaryFile: 'Meet my new oc BUNZThe hitman rabbit3rd art request from my fb friendsMixed media artTraditiona.webp',
    processFile: 'Meet my new oc BUNZThe hitman rabbit3rd art request from my fb friendsMixed media artTraditiona (1).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Traditional Ink Foundation',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Stylized anthropomorphic hitman character blending noir aesthetic with charismatic comic flair.',
    description: 'Created as an art request from friends, developing BUNZ: a lethal rabbit operative dressed in a sharp trenchcoat. Mixed media combining traditional ink contour lines with rich digital flat colors.',
    tags: ['Original Character', 'Noir', 'Character Design', 'Mixed Media']
  },
  {
    id: 'bipolar-concept',
    title: 'Bipolar Spectrum — Dual Psyche Study',
    category: 'Surrealism & Concept',
    filterCategory: 'surrealism',
    year: '2022',
    medium: 'Traditional Pen & Conceptual Line Art',
    primaryFile: 'Own concept practiceTheme- Mental illness ( bipolar disorder ) suggested by my friend on fbTrad.webp',
    processFile: 'Own concept practiceTheme- Mental illness ( bipolar disorder ) suggested by my friend on fbTrad (5).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Alternative Exposure',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Expressive conceptual study portraying the emotional dichotomy and psychological friction of mood extremes.',
    description: 'A conceptual study translating psychological struggle into surreal visual metaphor. Explores the tension between euphoria and despair through interconnected faces, twisting limbs, and dense hatching.',
    tags: ['Surrealism', 'Mental Health', 'Traditional Art', 'Metaphor']
  },
  {
    id: 'mikasa-ackerman',
    title: 'Mikasa Ackerman — Recreating Akari Minagawa',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: 'Digital Anime Keyframe Painting',
    primaryFile: 'DIGITAL ART❤️Mikasa AkermanRecreating Akari Minagawas(AOT animation director) Mikasa Illustrati.jpg',
    hasProcess: false,
    featured: true,
    aspectRatio: '4:5',
    caption: 'Tribute recreation of Attack on Titan animation director Akari Minagawa\'s iconic Mikasa illustration.',
    description: 'A master study and faithful recreation of Akari Minagawa\'s legendary Mikasa artwork from Attack on Titan: The Final Season. Focusing on gritty cinematic backlighting, scarf textures, and stoic determination.',
    tags: ['Attack on Titan', 'Mikasa Ackerman', 'Master Study', 'Anime Art']
  },
  {
    id: 'levi-ackerman',
    title: 'Captain Levi — Humanity\'s Strongest',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: 'Digital Speed Painting & Lighting Study',
    primaryFile: 'Now I realized I havent posted this yet. While checking on my IG profile, I wonder why my Levi.webp',
    altFile: 'Now I realized I havent posted this yet. While checking on my IG profile, I wonder why my Levi (1).webp',
    hasProcess: true,
    processType: 'full-to-crop',
    processLabel: 'Alternative Contrast',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Sharp, focused character study of Captain Levi Ackerman in high-contrast shadow and wind-swept motion.',
    description: 'Focused portrait study capturing Levi Ackerman\'s razor-sharp gaze and windswept cravat. High-contrast ambient occlusion and clean anatomical planes.',
    tags: ['Attack on Titan', 'Levi Ackerman', 'Character Study', 'Portrait']
  },
  {
    id: 'nero-dmc',
    title: 'Devil Trigger — Nero (Devil May Cry 5)',
    category: 'Character Art',
    filterCategory: 'character-art',
    year: '2022',
    medium: 'Digital Character Painting',
    primaryFile: 'Im back! 🦾After a long hiatus, Im finally posting again.Heres my fanart of Nero from Devil .webp',
    altFile: 'Im back! 🦾After a long hiatus, Im finally posting again.Heres my fanart of Nero from Devil  (1).webp',
    hasProcess: true,
    processType: 'full-to-crop',
    processLabel: 'Cropped Action View',
    featured: false,
    aspectRatio: '3:4',
    caption: 'Vibrant action portrait of Nero wielding the Devil Breaker prosthetic arm in saturated dynamic hues.',
    description: 'Painted following an artistic hiatus to celebrate Devil May Cry 5. Highlights the mechanical complexity of Nero\'s prosthetic arm alongside saturated comic-style facial rendering.',
    tags: ['Devil May Cry', 'Nero', 'Gaming Fan Art', 'Digital Painting']
  },
  {
    id: 'rock-lee',
    title: 'Green Beast of the Leaf — Rock Lee Collab',
    category: 'Collaborations',
    filterCategory: 'collaborations',
    year: '2022',
    medium: 'Digital Multi-Artist Collaboration',
    primaryFile: 'GREEN-THEMED COLLAB WITH THESE AMAZING ARTISTSMine - Rock Lee.webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '4:5',
    caption: 'Dynamic green-themed multi-artist collaboration entry showcasing Rock Lee with stylized martial arts dynamism.',
    description: 'Contributed as part of a curated green-palette collaborative challenge among digital illustrators. Spotlights Rock Lee\'s determination and ferocious hand-to-hand combat stance.',
    tags: ['Naruto', 'Rock Lee', 'Art Collaboration', 'Martial Arts']
  },
  {
    id: 'lara-tybur',
    title: 'Lara Tybur — War Hammer Titan Collab',
    category: 'Collaborations',
    filterCategory: 'collaborations',
    year: '2022',
    medium: 'Digital Titan Portrait & Hard Surface Study',
    primaryFile: 'First Digit Art CollaborationTheme- Attack on titanCharacters and ArtistsMine - Lara Tybur (War.webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '4:5',
    caption: 'First digital art collaboration piece depicting Lara Tybur\'s War Hammer Titan in stark alabaster armor.',
    description: 'Ronille\'s debut entry into community digital art collaborations. Explored hard-surface bone armor styling and crimson backdrop contrast for the War Hammer Titan from Attack on Titan.',
    tags: ['Attack on Titan', 'War Hammer Titan', 'Community Collab', 'Digital Art']
  },
  {
    id: 'aot-project-wit',
    title: 'Attack on Titan Fan Animation Contribution',
    category: 'Collaborations',
    filterCategory: 'collaborations',
    year: '2022',
    medium: 'Animation Key Art & Production Layout',
    primaryFile: 'Got a chance to be part of this fan animation project-@attackontitan_projectwit Im part of the.webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '4:5',
    caption: 'Contributed scene artwork for the global @attackontitan_projectwit community fan animation project.',
    description: 'Honored to contribute background layouts and scene keyframes for the collaborative @attackontitan_projectwit global fan animation, animating iconic scenes in the classic Studio WIT visual aesthetic.',
    tags: ['Animation', 'Studio WIT', 'Community Project', 'Keyframe Art']
  },
  {
    id: 'bleach-tokyo-ghoul',
    title: 'Ichigo x Kaneki — Bleach × Tokyo Ghoul',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2021',
    medium: 'Digital Crossover Illustration',
    primaryFile: 'LATE UPLOAD!!Just want to share my entry for@bleachartworks Bleach x Tokyo ghoul art contest15 .webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '4:5',
    caption: 'Dark fantasy crossover contest entry blending Bleach and Tokyo Ghoul hollow/ghoul aesthetic themes.',
    description: 'Official contest submission for the @bleachartworks crossover competition. Explored the symbiotic dark fantasy parallels between Ichigo Kurosaki\'s Hollow mask and Ken Kaneki\'s Kakugan eye.',
    tags: ['Bleach', 'Tokyo Ghoul', 'Crossover', 'Contest Entry']
  },
  {
    id: 'kurama-inktober',
    title: 'Baby Kurama — Inktober Day 21 (Fuzzy)',
    category: 'Traditional & Inks',
    filterCategory: 'traditional',
    year: '2021',
    medium: 'Traditional Ink Stippling & Hatching',
    primaryFile: 'INKTOBER DAY 21 - FUZZYBaby Kurama#inktober #inktober2021 #phxartfeatur #phx_artfeature #arttsh.webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '1:1',
    caption: 'Intricate traditional ink stippling and micro-hatching depicting the nine-tailed beast in its diminutive form.',
    description: 'Inktober Day 21 challenge with the prompt "Fuzzy". Rendered entirely by hand using technical ink pens, layering thousands of fine fur strokes and stippled shadow points to create tangible depth.',
    tags: ['Inktober', 'Traditional Ink', 'Naruto', 'Stippling']
  },
  {
    id: 'backpack-inktober',
    title: 'The Wanderer — Inktober Day 1 (Backpack)',
    category: 'Traditional & Inks',
    filterCategory: 'traditional',
    year: '2021',
    medium: 'Traditional Ink Line Art & Mixed Background',
    primaryFile: 'Too late but I dont care OCINKTOBER DAY 1- BACKPACK 🎒 Background from Pinterest Traditional I.webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '1:1',
    caption: 'Original character illustration for Inktober Day 1 featuring a street wanderer with an oversized adventure pack.',
    description: 'The inaugural piece of Inktober 2021. Demonstrates Ronille\'s clean line-weight modulation, natural cloth folds, and expressive character silhouette using traditional micron pens on paper.',
    tags: ['Inktober', 'Original Character', 'Traditional Art', 'Character Design']
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ARTWORKS };
}
