/**
 * Ronille Alcala (@nille.arts) - Artworks Catalog
 * Curated metadata for all 28 artwork assets in the images directory.
 */

const ARTWORKS = [
  {
    id: 'miles-morales',
    title: 'Across the Spider-Verse — Miles Morales',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2023',
    medium: 'Digital Illustration & Chromatic Halftone',
    primaryFile: 'HELLO! Im back with Miles! Havent watched the movie yet but Ive seen numerous artists creati.webp',
    hasProcess: false,
    featured: true,
    heroCandidate: true,
    aspectRatio: '4:5',
    caption: 'Dynamic perspective illustration capturing Miles Morales swinging through Neo-Manhattan with chromatic aberration and comic halftone styling.',
    description: 'A study in dynamic perspective, kinetic motion, and comic-book textures. Inspired by the visual language of Spider-Man: Across the Spider-Verse, balancing deep urban blues against intense magenta neon rim lights.',
    tags: ['Spider-Man', 'Marvel', 'Dynamic Motion', 'Comic Halftone']
  },
  {
    id: 'ekko-arcane',
    title: 'The Boy Who Shattered Time — Ekko',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: 'Digital Portrait & Chromatic Liquid Flow',
    primaryFile: 'The Boy who shattered TimeBest Boy of the seriesEkko fan art Style Inspired by @patrick.ganasMy.webp',
    hasProcess: false,
    featured: true,
    heroCandidate: true,
    aspectRatio: '4:5',
    caption: 'Split character portrait of Ekko from Arcane, blending stylized realism with iridescent chrome flourishes.',
    description: 'An homage to Ekko from Arcane, heavily inspired by stylized character illustrator Patrick Ganas. Exploring dual profile planes, textured dreadlock volumes, and iridescent chromatic splatter that mirrors temporal fractures.',
    tags: ['Arcane', 'League of Legends', 'Ekko', 'Stylized Realism']
  },
  {
    id: 'dabi-glow',
    title: 'Blue Flame — Toya Todoroki (Dabi)',
    category: 'Character Art',
    filterCategory: 'character-art',
    year: '2022',
    medium: 'Digital Illustration & Stylized Luminescence',
    primaryFile: 'Back to gloooww✨With new technique for semi realistic or stylized fireToya Todoroki- DabiForm M.webp',
    hasProcess: false,
    featured: true,
    aspectRatio: '4:5',
    caption: 'Moody atmospheric portrait exploring semi-realistic cobalt luminescence and glowing fire techniques.',
    description: 'A dedicated exploration of luminescent lighting on skin and folds. Using a specialized layering technique to achieve hyper-intense blue flame that casts crisp specular highlights across Dabi\'s silhouette.',
    tags: ['My Hero Academia', 'Dabi', 'Luminescence', 'Digital Painting']
  },
  {
    id: 'meltdown-surrealism',
    title: 'MELTDOWN — Severe Distress',
    category: 'Surrealism & Concept',
    filterCategory: ['surrealism', 'original-concept'],
    year: '2022',
    medium: 'Traditional Ink & Digital Color',
    primaryFile: 'MELTDOWN🕯️🫠This represents a severe, overwhelming emotional distress.Surealism ArtDrawn tradi.webp',
    processFile: 'MELTDOWN🕯️🫠This represents a severe, overwhelming emotional distress.Surealism ArtDrawn tradi (1).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Original Ink Linework',
    hasTraditionalDrawing: true,
    traditionalType: 'ink',
    traditionalTitle: 'MELTDOWN — Original Ink Linework',
    traditionalMedium: 'Traditional Ink Linework',
    traditionalFile: 'MELTDOWN🕯️🫠This represents a severe, overwhelming emotional distress.Surealism ArtDrawn tradi (1).webp',
    featured: true,
    aspectRatio: '4:5',
    caption: 'Surrealist metaphor depicting extreme emotional exhaustion and vulnerability as a melting candle portrait.',
    description: 'A deeply personal surrealist piece representing severe, overwhelming emotional distress. The piece started as an intricate traditional pen-and-ink drawing on cold-press paper with meticulous stippling, before being digitally colored with somber candlelit values.',
    tags: ['Surrealism', 'Original Concept', 'Mental Health', 'Traditional Ink', 'Process Piece']
  },
  {
    id: 'tetsuo-akira',
    title: 'Biomechanical Mutation — Tetsuo Shima (AKIRA)',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: 'Traditional Ink & Digital Screentone',
    primaryFile: 'Didnt expect to make this kind of artA fan art of Tetsuo Shima from the 1988 anime film AKIRAT.webp',
    processFile: 'Didnt expect to make this kind of artA fan art of Tetsuo Shima from the 1988 anime film AKIRAT (1).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Original Ink Linework',
    hasTraditionalDrawing: true,
    traditionalType: 'ink',
    traditionalTitle: 'Tetsuo Shima (AKIRA) — Original Ink Linework',
    traditionalMedium: 'Traditional Ink Linework',
    traditionalFile: 'Didnt expect to make this kind of artA fan art of Tetsuo Shima from the 1988 anime film AKIRAT (1).webp',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Intricate biomechanical line art celebrating Katsuhiro Otomo\'s 1988 cyberpunk masterpiece AKIRA.',
    description: 'Tribute to Katsuhiro Otomo\'s AKIRA. The grotesque cybernetic distortion of Tetsuo\'s arm was crafted using fine-liner pens, capturing every wire, piston, and fleshy mass, accented digitally by Tetsuo\'s iconic red cape.',
    tags: ['AKIRA', 'Cyberpunk', 'Traditional Inking', 'Biomechanical']
  },
  {
    id: 'denji-bad-habit',
    title: 'Bad Habit — Denji (Chainsaw Man)',
    category: 'Character Art',
    filterCategory: 'character-art',
    year: '2022',
    medium: 'Full Digital Illustration & Poster Design',
    primaryFile: 'Can I bite your tongue like my bad habitDenji fan art Reference- Bad habit by Steve LacyFirst.webp',
    altFile: 'Can I bite your tongue like my bad habitDenji fan art Reference- Bad habit by Steve LacyFirst (1).webp',
    hasProcess: true,
    processType: 'full-to-crop',
    processLabel: 'Full Bleed Close-Up',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Full digital illustration and poster inspired by the cover art of Steve Lacy\'s "Bad Habit" featuring Denji.',
    description: 'A full digital illustration and editorial poster design directly inspired by the cover image of Steve Lacy\'s hit song "Bad Habit", starring Denji from Chainsaw Man. Combines graphic color blocking, typography, and raw character expression.',
    tags: ['Chainsaw Man', 'Denji', 'Steve Lacy', 'Digital Illustration', 'Poster Design']
  },
  {
    id: 'cyborg-oc',
    title: 'Original Cyborg OC',
    category: 'Original Concept',
    filterCategory: 'original-concept',
    year: '2022',
    medium: 'Traditional Inking & Digital Color (Trad × Digi)',
    primaryFile: 'New CYBORG OCConcept and style inspired by Masamune Shirows Ghost in the Shell Traditional ink.webp',
    processFile: 'New CYBORG OCConcept and style inspired by Masamune Shirows Ghost in the Shell Traditional ink (3).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Original Ink Linework',
    hasTraditionalDrawing: true,
    traditionalType: 'ink',
    traditionalTitle: 'Original Cyborg OC — Original Ink Linework',
    traditionalMedium: 'Traditional Ink Linework',
    traditionalFile: 'New CYBORG OCConcept and style inspired by Masamune Shirows Ghost in the Shell Traditional ink (3).webp',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Original cyborg OC concept inspired by Masamune Shirow\'s Ghost in the Shell — traditional inking digitally colorized on Ibis Paint (Trad × Digi).',
    description: 'Concept and style inspired by Masamune Shirow\'s Ghost in the Shell. Created through traditional inking and digitally colorized on Ibis Paint (Trad × Digi), bridging hand-drawn linework with digital atmospheric coloring.',
    tags: ['Original Character', 'Ghost in the Shell', 'Trad x Digi', 'Ibis Paint', 'Cyberpunk', 'Anatomy']
  },
  {
    id: 'kaiju-no-8',
    title: 'Monstrous Rebirth — Kaiju No. 8',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: 'Traditional Inking & Digital Grayscale (Trad × Digi)',
    primaryFile: 'July Project Kaiju No. 8Traditional drawing to digital coloring using grayscale technique on Ib.webp',
    processFile: 'July Project Kaiju No. 8Traditional drawing to digital coloring using grayscale technique on Ib (1).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Original Ink Linework',
    hasTraditionalDrawing: true,
    traditionalType: 'ink',
    traditionalTitle: 'Kaiju No. 8 — Original Ink Linework',
    traditionalMedium: 'Traditional Ink Linework',
    traditionalFile: 'July Project Kaiju No. 8Traditional drawing to digital coloring using grayscale technique on Ib (1).webp',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Traditional inking digitally colored using the grayscale method on Ibis Paint (Trad × Digi).',
    description: 'Created through traditional inking and digitally colored using the grayscale method on Ibis Paint. Blends clean, detailed traditional ink linework with luminous digital values, textures, and atmospheric glowing accents.',
    tags: ['Kaiju No. 8', 'Traditional Inking', 'Grayscale Method', 'Ibis Paint', 'Trad x Digi', 'Fan Art']
  },
  {
    id: 'bunz-hitman-rabbit',
    title: 'BUNZ — The Hitman Rabbit',
    category: 'Original Concept',
    filterCategory: 'original-concept',
    year: '2022',
    medium: 'Traditional Pencil Hatching & Digital Color (Trad × Digi)',
    primaryFile: 'Meet my new oc BUNZThe hitman rabbit3rd art request from my fb friendsMixed media artTraditiona.webp',
    processFile: 'Meet my new oc BUNZThe hitman rabbit3rd art request from my fb friendsMixed media artTraditiona (1).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Traditional Hatching Drawing',
    hasTraditionalDrawing: true,
    traditionalType: 'pencil',
    traditionalTitle: 'BUNZ (The Hitman Rabbit) — Traditional Hatching Drawing',
    traditionalMedium: 'Traditional Pencil Hatching',
    traditionalFile: 'Meet my new oc BUNZThe hitman rabbit3rd art request from my fb friendsMixed media artTraditiona (1).webp',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Original hitman rabbit OC created with traditional pencil drawing using the hatching method and digitally colorized.',
    description: 'Created as an art request from friends, developing BUNZ: a lethal rabbit operative dressed in a sharp trenchcoat. Mixed media combining traditional pencil drawing using the hatching method with rich digital colorization.',
    tags: ['Original Character', 'Pencil Hatching', 'Trad x Digi', 'Character Design', 'Mixed Media']
  },
  {
    id: 'bipolar-concept',
    title: 'Bipolar Spectrum — Dual Psyche Study',
    category: 'Surrealism & Concept',
    filterCategory: ['surrealism', 'original-concept'],
    year: '2022',
    medium: 'Traditional Pencil Hatching & Digital Color (Trad × Digi)',
    primaryFile: 'Own concept practiceTheme- Mental illness ( bipolar disorder ) suggested by my friend on fbTrad.webp',
    processFile: 'Own concept practiceTheme- Mental illness ( bipolar disorder ) suggested by my friend on fbTrad (5).webp',
    hasProcess: true,
    processType: 'ink-to-color',
    processLabel: 'Original Pencil Linework',
    hasTraditionalDrawing: true,
    traditionalType: 'pencil',
    traditionalTitle: 'Bipolar Spectrum — Original Pencil Linework',
    traditionalMedium: 'Traditional Pencil Drawing (Hatching Method)',
    traditionalFile: 'Own concept practiceTheme- Mental illness ( bipolar disorder ) suggested by my friend on fbTrad (5).webp',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Expressive conceptual study on bipolar disorder created with traditional pencil hatching and digitally colored.',
    description: 'A conceptual artwork exploring the theme of bipolar disorder. Created purely through traditional pencil drawing using intricate hatching techniques without any inking, then digitally colorized to capture the emotional dichotomy of the psyche.',
    tags: ['Surrealism', 'Original Concept', 'Mental Health', 'Pencil Hatching', 'Trad x Digi', 'Concept Art']
  },
  {
    id: 'mikasa-ackerman',
    title: 'Mikasa Ackerman — Recreating Akari Minagawa',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: 'Digital Anime Illustration (WIT Studio Style)',
    primaryFile: 'DIGITAL ART❤️Mikasa AkermanRecreating Akari Minagawas(AOT animation director) Mikasa Illustrati.jpg',
    hasProcess: false,
    featured: true,
    aspectRatio: '4:5',
    caption: 'Recreation of AOT animation director Akari Minagawa\'s Mikasa illustration, rendered in own style inspired by Studio WIT.',
    description: 'A recreation of Attack on Titan animation director Akari Minagawa\'s illustration of Mikasa Ackerman, reimagined in Ronille\'s personal style inspired by Studio WIT. Emphasizes dramatic cinematic lighting, bold line definition, and Mikasa\'s resolute, stoic gaze.',
    tags: ['Attack on Titan', 'Mikasa Ackerman', 'Studio WIT Style', 'Akari Minagawa', 'Digital Art']
  },
  {
    id: 'levi-ackerman',
    title: 'Captain Levi — Studio WIT Style (Project WIT)',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: 'Digital Keyframe Illustration',
    primaryFile: 'Now I realized I havent posted this yet. While checking on my IG profile, I wonder why my Levi.webp',
    altFile: 'Now I realized I havent posted this yet. While checking on my IG profile, I wonder why my Levi (1).webp',
    hasProcess: true,
    processType: 'full-to-crop',
    processLabel: 'Raw Key Frame',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Final illustration for @attackontitan_projectwit depicting Captain Levi in The Final Season rendered in the iconic Studio WIT style.',
    description: 'The final illustration contributed to the @attackontitan_projectwit project. Depicts Captain Levi Ackerman from The Final Season reimagined in Studio WIT\'s classic visual and animation style, featuring raw keyframe linework and intense dramatic lighting.',
    tags: ['Attack on Titan', 'Levi Ackerman', 'Studio WIT', 'Project WIT', 'Keyframe Art', 'Final Season']
  },
  {
    id: 'nero-dmc',
    title: 'Devil Trigger — Nero (Devil May Cry 5)',
    category: 'Character Art',
    filterCategory: 'character-art',
    year: '2022',
    medium: 'Digital Character Painting',
    primaryFile: 'Im back! 🦾After a long hiatus, Im finally posting again.Heres my fanart of Nero from Devil .webp',
    altFile: 'Im back! 🦾After a long hiatus, Im finally posting again.Heres my fanart of Nero from Devil  (1).webp',
    hasProcess: true,
    processType: 'full-to-crop',
    processLabel: 'Original Pencil Linework',
    hasTraditionalDrawing: true,
    traditionalType: 'pencil',
    traditionalTitle: 'Nero (Devil May Cry 5) — Original Pencil Linework',
    traditionalMedium: 'Traditional Pencil Linework',
    traditionalFile: 'Im back! 🦾After a long hiatus, Im finally posting again.Heres my fanart of Nero from Devil  (1).webp',
    featured: false,
    aspectRatio: '3:4',
    caption: 'Vibrant action portrait of Nero wielding the Devil Breaker prosthetic arm in saturated dynamic hues.',
    description: 'Painted following an artistic hiatus to celebrate Devil May Cry 5. Highlights the mechanical complexity of Nero\'s prosthetic arm alongside saturated comic-style facial rendering.',
    tags: ['Devil May Cry', 'Nero', 'Gaming Fan Art', 'Digital Painting']
  },
  {
    id: 'rock-lee',
    title: 'Green Beast of the Leaf — Rock Lee Collab',
    category: 'Collaborations',
    filterCategory: 'collaborations',
    year: '2022',
    medium: 'Digital Multi-Artist Collaboration',
    primaryFile: 'GREEN-THEMED COLLAB WITH THESE AMAZING ARTISTSMine - Rock Lee.webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '4:5',
    caption: 'Dynamic green-themed multi-artist collaboration entry showcasing Rock Lee with stylized martial arts dynamism.',
    description: 'Contributed as part of a curated green-palette collaborative challenge among digital illustrators. Spotlights Rock Lee\'s determination and ferocious hand-to-hand combat stance.',
    tags: ['Naruto', 'Rock Lee', 'Art Collaboration', 'Martial Arts']
  },
  {
    id: 'lara-tybur',
    title: 'Lara Tybur — War Hammer Titan Collab',
    category: 'Collaborations',
    filterCategory: 'collaborations',
    year: '2022',
    medium: 'Digital Titan Portrait & Hard Surface Study',
    primaryFile: 'First Digit Art CollaborationTheme- Attack on titanCharacters and ArtistsMine - Lara Tybur (War.webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '4:5',
    caption: 'First digital art collaboration piece depicting Lara Tybur\'s War Hammer Titan in stark alabaster armor.',
    description: 'Ronille\'s debut entry into community digital art collaborations. Explored hard-surface bone armor styling and crimson backdrop contrast for the War Hammer Titan from Attack on Titan.',
    tags: ['Attack on Titan', 'War Hammer Titan', 'Community Collab', 'Digital Art']
  },
  {
    id: 'aot-project-wit',
    title: 'Mikasa Ackerman — Studio WIT Style (Project WIT)',
    category: 'Collaborations',
    filterCategory: 'collaborations',
    year: '2022',
    medium: 'Keyframe Drawing & Colored Digital Illustration',
    primaryFile: 'Got a chance to be part of this fan animation project-@attackontitan_projectwit Im part of the.webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '4:5',
    caption: 'Contributed keyframe drawing and colored illustration for @attackontitan_projectwit featuring Mikasa in The Final Season in Studio WIT style.',
    description: 'Contributed to the collaborative @attackontitan_projectwit global fan animation project with a single keyframe drawing and a full-colored illustration. Depicts Mikasa Ackerman from Attack on Titan: The Final Season reimagined in the classic Studio WIT animation aesthetic.',
    tags: ['Attack on Titan', 'Mikasa Ackerman', 'Studio WIT', 'Project WIT', 'Keyframe Art', 'Final Season']
  },
  {
    id: 'bleach-tokyo-ghoul',
    title: 'Juuzou x Luppi (Fusion) — Bleach × Tokyo Ghoul',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2021',
    medium: 'Digital Crossover Illustration',
    primaryFile: 'LATE UPLOAD!!Just want to share my entry for@bleachartworks Bleach x Tokyo ghoul art contest15 .webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '4:5',
    caption: 'Contest entry for the Bleach × Tokyo Ghoul art contest featuring an original fusion of Juuzou Suzuya and Luppi Antenor.',
    description: 'Official contest submission for the @bleachartworks Bleach × Tokyo Ghoul crossover competition. An original fusion concept blending Juuzou Suzuya (Tokyo Ghoul) and Luppi Antenor (Bleach), capturing their eccentric, chaotic energy and deadly flair.',
    tags: ['Bleach', 'Tokyo Ghoul', 'Juuzou Suzuya', 'Luppi Antenor', 'Fusion', 'Contest Entry']
  },
  {
    id: 'kurama-inktober',
    title: 'Baby Kurama — Inktober Day 21 (Fuzzy)',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2021',
    medium: 'Traditional Ink Stippling & Hatching',
    primaryFile: 'INKTOBER DAY 21 - FUZZYBaby Kurama#inktober #inktober2021 #phxartfeatur #phx_artfeature #arttsh.webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '1:1',
    caption: 'Intricate traditional ink stippling and micro-hatching depicting the nine-tailed beast in its diminutive form.',
    description: 'Inktober Day 21 challenge with the prompt "Fuzzy". Rendered entirely by hand using technical ink pens, layering thousands of fine fur strokes and stippled shadow points to create tangible depth.',
    tags: ['Inktober', 'Traditional Ink', 'Naruto', 'Stippling', 'Fan Art']
  },
  {
    id: 'backpack-inktober',
    title: 'The Wanderer — Inktober Day 1 (Backpack)',
    category: 'Original Concept',
    filterCategory: 'original-concept',
    year: '2021',
    medium: 'Traditional Ink Line Art & Mixed Background',
    primaryFile: 'Too late but I dont care OCINKTOBER DAY 1- BACKPACK 🎒 Background from Pinterest Traditional I.webp',
    hasProcess: false,
    featured: false,
    aspectRatio: '1:1',
    caption: 'Original character illustration for Inktober Day 1 featuring a street wanderer with an oversized adventure pack.',
    description: 'The inaugural piece of Inktober 2021. Demonstrates Ronille\'s clean line-weight modulation, natural cloth folds, and expressive character silhouette using traditional micron pens on paper.',
    tags: ['Inktober', 'Original Character', 'Traditional Art', 'Character Design']
  },
  {
    id: 'denji-chainsaw-pencil',
    title: 'Chainsaw Devil — Denji (Chainsaw Man)',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2022',
    medium: '0.5 Mechanical Pencil & 6B Pencil on Vellum Board',
    primaryFile: 'Chainsaw man fanart🔥Character- DenjiMaterials- 0.5 mechanical pencil and 6b pencil on vellum bo.jpg',
    hasProcess: false,
    hasTraditionalDrawing: true,
    traditionalType: 'pencil',
    traditionalTitle: 'Chainsaw Devil (Denji) — Traditional Pencil Drawing',
    traditionalMedium: '0.5 Mechanical Pencil & 6B Pencil on Vellum Board',
    traditionalFile: 'Chainsaw man fanart🔥Character- DenjiMaterials- 0.5 mechanical pencil and 6b pencil on vellum bo.jpg',
    featured: false,
    aspectRatio: '3:4',
    caption: 'Intricate traditional pencil drawing of Denji in Chainsaw Devil form, shaded on vellum board.',
    description: 'A high-intensity traditional pencil illustration of Denji from Chainsaw Man. Rendered using 0.5mm mechanical pencils for razor-sharp mechanical teeth and chain linkages, layered with deep 6B graphite values on smooth vellum board.',
    tags: ['Chainsaw Man', 'Denji', 'Traditional Pencil', 'Graphite Art', 'Fan Art']
  },
  {
    id: 'freehand-portrait-study',
    title: 'Freehand Portrait Study — Pencil Hatching',
    category: 'Character Art',
    filterCategory: 'character-art',
    year: '2022',
    medium: 'Traditional Graphite Pencil on Paper',
    primaryFile: 'Freehand portraitRandom reference from PinterestArt style inspired by- Josh ArtI just made a tw.webp',
    hasProcess: false,
    hasTraditionalDrawing: true,
    traditionalType: 'pencil',
    traditionalTitle: 'Freehand Portrait Study — Traditional Pencil',
    traditionalMedium: 'Traditional Graphite Pencil on Paper',
    traditionalFile: 'Freehand portraitRandom reference from PinterestArt style inspired by- Josh ArtI just made a tw.webp',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Freehand pencil portrait study exploring facial planes, cross-hatching, and subtle expressive gaze.',
    description: 'A freehand traditional pencil portrait study inspired by the artistic style of Josh Art. Executed with directional hatching and tonal value control to sculpt facial anatomy, hair flow, and a calm, contemplative gaze.',
    tags: ['Portrait Study', 'Traditional Pencil', 'Freehand Drawing', 'Cross Hatching', 'Character Art']
  },
  {
    id: 'rock-lee-gaara',
    title: 'Leaf Hurricane — Rock Lee vs. Gaara (Naruto)',
    category: 'Fan Art',
    filterCategory: 'fan-art',
    year: '2021',
    medium: 'Traditional Graphite Pencil on Paper',
    primaryFile: 'Photography is an immediate reaction, Drawing is a meditation - Henri Cartier-Bresson#tebandw @t.jpg',
    hasProcess: false,
    hasTraditionalDrawing: true,
    traditionalType: 'pencil',
    traditionalTitle: 'Leaf Hurricane (Rock Lee vs. Gaara) — Traditional Pencil',
    traditionalMedium: 'Traditional Graphite Pencil on Paper',
    traditionalFile: 'Photography is an immediate reaction, Drawing is a meditation - Henri Cartier-Bresson#tebandw @t.jpg',
    featured: false,
    aspectRatio: '4:5',
    caption: 'Dynamic traditional pencil drawing capturing Rock Lee\'s extreme foreshortened kick against Gaara.',
    description: '"Drawing is a meditation." A dynamic traditional graphite illustration paying tribute to the legendary Chunin Exams battle between Rock Lee and Gaara from Naruto. Employs dramatic wide-angle perspective, motion sweeps, and intricate pencil tonal gradations.',
    tags: ['Naruto', 'Rock Lee', 'Gaara', 'Traditional Pencil', 'Foreshortening', 'Fan Art']
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ARTWORKS };
}
